spring.application.name=boors-azma-api
spring.datasource.url=jdbc:postgresql://localhost:5432/boors
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
app.security.jwt.secret=change-this-secret-key-at-least-32-bytes-long-for-jwt-signing
app.security.jwt.access-token-minutes=1000
app.market-search.csv-path=market.csv
springdoc.swagger-ui.path=/doc.html
app.bootstrap.admin.username:erfan
app.bootstrap.admin.email:erfan@gmail.com
app.bootstrap.admin.phone-number:+989123456789
app.bootstrap.admin.national-code:1111111111
app.bootstrap.admin.first-name:erfan
app.bootstrap.admin.last-name:dn
app.bootstrap.admin.password:12345678
app.bootstrap.admin.balance:12345678
